### ISSUE TITLE
Attributions manquantes

### ISSUE THREAD

**Issue by JVillafruela** [LaphazeMC/CovidRadius#1]
Bravo pour l'appli ! J'ai remarqué qu'il manque les attributions :

- https://docs.mapbox.com/help/how-mapbox-works/attribution/
- https://www.openstreetmap.org/copyright

**Comment by LaphazeMC** [comment]
Hello @JVillafruela,

Merci beaucoup pour ce retour !
Fixed in https://github.com/LaphazeMC/CovidRadius/commit/9825803bad885f6c5af1ca04004011bbac08c42a
