### ISSUE TITLE
Remplacement map?

### ISSUE THREAD

**Issue by loicortola** [LaphazeMC/CovidRadius#2]
Hello Maxime,

bravo pour l'initiative :)
Si vous commencez à avoir des maps payantes, je serais ravi de vous offrir un Token Jawg Maps instead, avec des quotas illimités pour le service !
Idem pour le géocoding ;)

Joyeues Paques, je vais me balader dans un rayon de 1km... ^^

Loïc

**Comment by LaphazeMC** [comment]
Hello @loicortola,

Merci pour ce retour, et merci énormément pour cette proposition !
Je ne manquerai pas de revenir vers vous si l'occasion se présente.
