### ISSUE TITLE
texte mensonger

### ISSUE THREAD

**Issue by Shnoulle** [LaphazeMC/CovidRadius#3]
Aucune donnée n'est stockée ni récupérée : peut être par le site mais pas par google.

De plus non fonctionnel avec [privacybadger](https://privacybadger.org/) (api-adresse.data.gouv.fr est bloqué : utilisation de cookie de suivi ? )

**Comment by LaphazeMC** [comment]
Je vais changer ce texte de manière plus précise en ajoutant que, les adresses postales saisies ne sont pas stockées car c'est effectivement le cas, nous n'avons pas de back-end qui récupère et stock ces données.

![image](https://user-images.githubusercontent.com/17979718/81784994-01249480-94fe-11ea-909f-07263ca4e3fa.png)
Je ne vois pas d'erreur avec privacyBadger concernant l'api du gouvernement ? Les seules erreurs qu'il y a sont liées à google ads, qui nous permet de palier les coûts d'infrastructure / API calls car le trafic est très important dernièrement (1M+ de visiteurs uniques en 4 semaines)

**Comment by Shnoulle** [comment]
Pour adresse : il faut commencer une recherche (et sans doute avoir déjà rencontré la même API avant)
![Capture d’écran du 2020-05-13 09-54-44](https://user-images.githubusercontent.com/1439428/81786470-ff5bd080-94ff-11ea-94df-47c8ef7077ca.png)

(en fait : chez moi : googlesyndication est bloqué par ublock, pour rappel : privacybadger utilise un blocage dynamique)

**Comment by LaphazeMC** [comment]
Yes j'imagine que le soucis vient d'une utilisation antérieure avec api-adresse.data.gouv.fr car je n'ai absolument rien même en faisant des recherches nominatim sur covidradius.

En tout cas merci pour ces retours et la découverte de privacy badger, je vais ajouter l'update dans la journée pour le changement du label.
